### PR TITLE
O3-2890 Add ability to edit bill line item

### PR DESCRIPTION
**Pull request by CynthiaKamau**
## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Summary

O3-2890 Add ability to edit bill line item

## Screenshots

https://github.com/openmrs/openmrs-esm-billing-app/assets/19533785/67bd5de7-a097-4b9f-87bc-c33adf745989

### CODE REVIEW

**Comment by jecihjoy** [comment]
@CynthiaKamau thanks for looking into this, however I believe we would wish to control who can edit the bill, I believe the edit bill functionality would usually be done by the cashier, that said the cashiers are limited to interract with the patients bills only through the billing dashboard, with that in mind the edit functionality is better off placed in the cashier dasboard, also the cashier could be restricted to only edit the quantity and billables prices should entirely be managed from the billable services dashboard by admins 

Generally the edit functionality could introduce some loopholes that we would wish to avoid hence I believe we should interrogate further the need for this functionality

**Comment by CynthiaKamau** [comment]
> @CynthiaKamau thanks for looking into this, however I believe we would wish to control who can edit the bill, I believe the edit bill functionality would usually be done by the cashier, that said the cashiers are limited to interract with the patients bills only through the billing dashboard, with that in mind the edit functionality is better off placed in the cashier dasboard, also the cashier could be restricted to only edit the quantity and billables prices should entirely be managed from the billable services dashboard by admins
> 
> Generally the edit functionality could introduce some loopholes that we would wish to avoid hence I believe we should interrogate further the need for this functionality

Thanks @jecihjoy for the input, i have added a config for the functionality. In terms of permissions, the edit button is an extension and implementors can configure their preferred permissions through configs.

**Comment by jecihjoy** [comment]
> > @CynthiaKamau thanks for looking into this, however I believe we would wish to control who can edit the bill, I believe the edit bill functionality would usually be done by the cashier, that said the cashiers are limited to interract with the patients bills only through the billing dashboard, with that in mind the edit functionality is better off placed in the cashier dasboard, also the cashier could be restricted to only edit the quantity and billables prices should entirely be managed from the billable services dashboard by admins
> > Generally the edit functionality could introduce some loopholes that we would wish to avoid hence I believe we should interrogate further the need for this functionality
> 
> Thanks @jecihjoy for the input, i have added a config for the functionality. In terms of permissions, the edit button is an extension and implementors can configure their preferred permissions through configs.

@CynthiaKamau that works, I've seen it also defaulted to false

**Review by ODORA0 — APPROVED** [review]
LGTM

**Pull request merged**
